# Copyright (c) Devolutions & contributors
# GitHub: Devolutions/IronRDP
# Source: https://github.com/Devolutions/IronRDP/blob/bdde2c76ded7315f7bc91d81a0909a1cb827d870/crates/ironrdp-web/rust-toolchain.toml

[toolchain]
targets = ["wasm32-unknown-unknown"]
profile = "minimal"
